---
title: "Analysis_smFISH_SypGFP_mutant_NMJ"
output: pdf_document
date: "2023-09-08"
editor_options: 
  chunk_output_type: console
---
# R ENVIRONMENT 

```{r}
library(tidyverse)
library(patchwork)
library(rstatix)
library(ggplot2)
library(ggbeeswarm)
library(ggpubr)
library(readr)
`%!in%` = Negate(`%in%`)
```

# Import smFISH molecules in Syp GFP/mutant data
```{r}
dataframe <- read_csv("./Data/CH5_Lac_exon_Syp_GFP_mutant/final_results_Syp_smFISH.csv")
```

# Clean dataframe
```{r}
clean_molecules <- dataframe %>%
  mutate(condition = case_when(
    str_detect(Filename, "GFP") ~ "Control",
    str_detect(Filename, "mutant") ~ "Syp mutant")) %>%
  rename("no_mRNA_molecules" = "Common Coordinates")
```

#Check if normal
```{r}
clean_molecules %>%
  group_by(condition) %>%
  shapiro_test(no_mRNA_molecules) %>%
  add_significance() %>%
  ungroup()
```

# Perform stats
```{r}
stats <- clean_molecules %>%
  t_test(no_mRNA_molecules ~ condition) %>%
  add_significance()
```

# Plot
```{r}
clean_molecules$condition <- factor(clean_molecules$condition, levels = c("Control", "Syp mutant"))

ggplot(clean_molecules, aes(x = condition, y = no_mRNA_molecules)) +
  geom_jitter(width = 0.1, alpha = 0.3, size = 4) +
  stat_summary(fun = mean, geom = "crossbar", width = 0.45, size = 0.6, color = "#C53270") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, color = "#C53270", size = 1) +
  stat_compare_means(comparisons = list(c("Control", "Syp mutant")), method = "t.test", label = "p.signif") +
  theme_classic2() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  theme(plot.title = element_text(size = 10),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 8))+
  labs(x = NULL,
       title = "Lac mRNA molecules in NMJ axon terminal projections in Syp mutant",
       y = expression(paste("Number of Lac mRNA molecules in the axon terminal projections")))

ggsave("./Thesis-Scripts/Output/Plots/CH5_Syp_mutant_Lac_Molecules.pdf",
       width = 10 * 0.5, height = 8 * 0.5,
       device = cairo_pdf)
```
