---
title: "Area_analysis_KStim_dev"
output: html_document
date: "2023-08-15"
editor_options: 
  chunk_output_type: console
---

## Libraries
```{r}
library(tidyverse)
library(rstatix)
library(patchwork)
library(furrr)
library(colorspace)
library(ggpubr)
```

## Read files in - KStim
```{r}
Kstim_area_raw <- list.files(
    "./Data/CH4_KStim_areas/",
    pattern = "*.csv",
    full.names = TRUE
  ) %>%
  map(read_csv)
```

## Read files in - dev
```{r}
dev_area_raw <- list.files(
    "./Data/CH4_Dev_areas/",
    pattern = "*.csv",
    full.names = TRUE
  ) %>%
  map(read_csv)
```

## Get stats and summaries = dev areas
```{r}
dev_area_statistics <- dev_area_raw %>%
    map_dfr(~ {
        dev_area_cleaned <- .x %>%
            mutate(Label = str_replace(Label, "_C[:digit:].tif", "")) %>%
            pivot_wider(id_cols = c(Label, condition), values_from = sum_Area, names_from = channel) %>%
            dplyr::rename("Neurite" = HRP) %>%
            mutate(ratio_Glia_Neurite = Glia / Neurite) %>%
            pivot_longer(cols = c(Glia, Neurite, ratio_Glia_Neurite), names_to = "type")

        dev_area_mean <- dev_area_cleaned %>%
            group_by(condition, type) %>%
            summarise(
                mean = mean(value)
            ) %>%
            ungroup()

        dev_area_foldchange <- left_join(
            filter(dev_area_mean, condition != "Control"),
            filter(dev_area_mean, condition == "Control") %>%
                dplyr::select(type, "control_mean" = mean),
            by = "type"
        ) %>%
            mutate(foldchange = mean / control_mean)

        dev_area_statistics <- dev_area_cleaned %>%
            group_by(type) %>%
            t_test(value ~ condition, ref.group = "Control", p.adjust.method = "bonferroni") %>%
            { 
                if ("p.adj" %in% names(.)) {
                    mutate(., 
                        p = if_else(is.na(p.adj), p, p.adj),
                        adjusted = !is.na(p.adj)
                    ) %>%
                    dplyr::select(type, "condition" = group2, statistic, p, starts_with("n"), adjusted)
                } else {
                    mutate(., adjusted = FALSE) %>%
                    dplyr::select(type, "condition" = group2, statistic, p, starts_with("n"), adjusted)
                }
            } %>%
            left_join(dev_area_foldchange, by = c("type", "condition"))
    })
```

## Get stats and summaries = Kstim areas
```{r}
Kstim_area_statistics <- Kstim_area_raw %>%
    map_dfr(~ {
        dev_area_cleaned <- .x %>%
            mutate(Label = str_replace(Label, "_C[:digit:].tif", "")) %>%
            pivot_wider(id_cols = c(Label, condition), values_from = sum_Area, names_from = channel) %>%
            dplyr::rename("Neurite" = HRP) %>%
            mutate(ratio_Glia_Neurite = Glia / Neurite) %>%
            pivot_longer(cols = c(Glia, Neurite, ratio_Glia_Neurite), names_to = "type")

        dev_area_mean <- dev_area_cleaned %>%
            group_by(condition, type) %>%
            summarise(
                mean = mean(value)
            ) %>%
            ungroup()

        dev_area_foldchange <- left_join(
            filter(dev_area_mean, condition != "Control"),
            filter(dev_area_mean, condition == "Control") %>%
                dplyr::select(type, "control_mean" = mean),
            by = "type"
        ) %>%
            mutate(foldchange = mean / control_mean)

        dev_area_statistics <- dev_area_cleaned %>%
            group_by(type) %>%
            t_test(value ~ condition, ref.group = "Control") %>%
            dplyr::select(type, "condition" = group2, statistic, p, starts_with("n")) %>%
            left_join(dev_area_foldchange, by = c("type", "condition"))
    })
```


## Rename genes for dev areas
```{r}
id_change <- tibble(
  input = unique(dev_area_statistics$condition),
  ens99_name = c("Gli", "α-Cat", "Atpα", "CG42342", "Gs2", "kst", "lost", "Nrg", "nrv2", "Pdi", "sdk", "Lac", "cold", "shot", "CG1648", "Flo2", "Vha55"))
```

## Rename genes for KStim areas
```{r}
id_change <- tibble(
  input = unique(Kstim_area_statistics$condition),
  ens99_name = c("α-Cat", "Atpα", "Flo2", "CG1648", "CG42342", "sdk", "Gli","Gs2", "kst", "Lac", "lost", "Nrg", "Pdi", "cold", "nrv2","shot", "Vha55"))
``` 

## Get stats
```{r}
# To analyse, assign desired statistics to area_statistics_for_plotting (Kstim_area_statistics or dev_area_statistics)
area_statistics_for_plotting <- Kstim_area_statistics %>%
  mutate(p = case_when(
    p < 0.0001 ~ "**** < 0.0001",
    p < 0.001 ~ "*** < 0.001",
    p < 0.01 ~ "** < 0.01",
    p < 0.05 ~ "* < 0.05",
    TRUE ~ "N.S."
  )) %>%
  mutate(type = case_when(
    type == "Glia" ~ "Glial area",
    type == "Neurite" ~ "Neurite area",
    type == "ratio_Glia_Neurite" ~ "Ratio Glial/Neurite"
  )) %>%
  left_join(id_change, by = c("condition" = "input"))
```

## Save a csv
```{r}
write_csv(area_statistics_for_plotting, "./Output/KStim_analysis/Kstim_area_summary_statistics_tidy.csv")
```

## Alternatively read in an old csv
```{r}
area_statistics_for_plotting <- read_csv("./Output/Kstim_analysis/Areas_output/Kstim_area_summary_statistics_tidy.csv")
```

## Set specifics and plot
```{r}
# For dev areas
colours <- c(sequential_hcl(n = 7, palette = "Inferno", rev = FALSE)[2:5], "gray70")
# For Kstim areas
# colours <- c(sequential_hcl(n = 7, palette = "Inferno", rev = FALSE)[2:5], "gray70")

gene_order_dev <- area_statistics_for_plotting %>%
  filter(type == "Glial area") %>%
  arrange(desc(foldchange)) %>% pull(ens99_name)

area_statistics_for_plotting %>%
  mutate(ens99_name = fct_relevel(ens99_name, gene_order_dev)) %>%
  ggplot(aes(x = ens99_name, y = foldchange, colour = p)) +
  geom_segment(aes(xend = ens99_name, y = 1, yend = foldchange), colour = "gray50", size = 0.3) + 
  geom_point(size = 1.5) + 
  geom_hline(yintercept = 1, linetype = "dashed", colour = "gray70", size = 0.2) +
  coord_flip(ylim = c(0.5, 2)) +
  labs(
    x = "", 
    y = "Average foldchange over stimulated Control",
    colour = "P-value"
  ) + 
  scale_colour_manual(values = colours) + 
  facet_wrap(~ type) +
  theme_bw(base_size = 6) + 
  theme(
    legend.text = element_text(size = 4),
    legend.title = element_text(size = 5),
    axis.text.x = element_text(size = 3)
    ) +
  guides(colour = guide_legend(keywidth = 0.1, keyheight = 0.5)) -> dev_plot

dev_plot

# Save figure
ggsave("./Output/Plots/phenotype_plot_Kstim_areas_3102023.pdf",
       width = 11 * 0.3937, height = 5 * 0.38937,
       device = cairo_pdf)
```

```{r}
lac <- read_csv("./Data/CH4_KStim_areas/Kstim_areas_lac.csv")
```

```{r}
areas <- lac %>%
  filter(.$channel == "HRP") %>%
  group_by(day) %>%
  count(condition)
```

```{r}
lac_areas <-
  lac%>%
  filter(day == 2) %>%
  mutate(day = NULL)
```


```{r}
lac %>%
  filter(.$channel == "HRP") %>%
  ggplot(aes(x = condition, y = sum_Area)) +
  geom_boxplot()+
  stat_compare_means(comparisons = list(c("Control", "lac")), method="wilcox.test", label="p.signif")+
  facet_wrap(~day)
```

```{r}
lac_btns <- read_csv("./Data/CH4_KStim_boutons/CG42342_lac_all.csv")
```

```{r}
lac_btns <-
  lac_btns%>%
  filter(Set != "CG42342") %>%
  filter(Replicate == 5) %>%
  mutate(Replicate = NULL)
```

```{r}
write_csv(lac_areas, "./Data/CH4_KStim_areas/Kstim_areas_lac_VDRC.csv")
```

