---
title: "Area_analysis_glial_subtypes"
output: pdf_document
date: "2023-09-11"
editor_options: 
  chunk_output_type: console
---
## Libraries
```{r}
library(tidyverse)
library(rstatix)
library(patchwork)
library(furrr)
library(colorspace)
library(ggplot2)
library(ggbeeswarm)
library(ggpubr)
library(ggforce)
library(viridis)
`%!in%` = Negate(`%in%`)
options(scipen=999)
library(reshape2)
```

## Read files in - KStim
```{r}
perineurial.df <- read_csv("./Data/CH5_Glial_Areas_Subtype_Analysis/Clean_dfs/Results_Area_46F_GAL4_clean.csv")
subperineurial.df <- read_csv("./Data/CH5_Glial_Areas_Subtype_Analysis/Clean_dfs/Results_Area_Mdr65_GAL4_clean.csv")
wrapping.df <- read_csv("./Data/CH5_Glial_Areas_Subtype_Analysis/Clean_dfs/Results_Area_Nrv2_GAL4_clean.csv")
```

## Missing files
```{r}
## Read FIJI output and add missing file
# file_list = list.files(path ="/Volumes/Dalia_Data/Area Analysis Glial Subtypes/Mdr/Mdr_Repo_Output_Triangle/", pattern = "*.tif", all.files = FALSE,
#                        full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
# 
# for (f in file_list) {
#   f = str_replace(f, "^ROI_", "")
#   if (f %!in% subperineurial.df$Label)
#     subperineurial.df = add_row(subperineurial.df, Label = f, Area = 0)
# }

# write_csv(subperineurial.df, "./Data/CH5_Glial_Areas_Subtype_Analysis/Results_Area_Mdr65_GAL4_empty_added.csv")
```

## Clean dataframe
```{r}
# Wrapping data - Nrv2-GAL4
# df <- wrapping.df %>%
#   group_by(Label) %>%
#   summarise(sum_Area = sum(Area)) %>%
#   ungroup() %>%
#   mutate(condition = case_when(
#     str_detect(Label, "Repo_GFP_CTRL") ~ "Repo Control",
#     str_detect(Label, "Nrv2_GFP_CTRL") ~ "Nrv2 Control",
#     str_detect(Label, "Nrv2_GFP_GD") ~ "Nrv2>Lac RNAi",
#     str_detect(Label, "Repo_GFP_GD") ~ "Repo>Lac RNAi")) %>%
#   mutate(channel = case_when(
#     str_detect(Label, "C1") ~ "Glial projection area",
#     TRUE ~ "Motor neuron axon projection area")) %>%
#   na.omit()
# 
# df$sum_Area[df$sum_Area > 1000] <- 0
# write_csv(df, "./Data/CH5_Glial_Areas_Subtype_Analysis/Clean_dfs/Results_Area_Nrv2_GAL4_clean.csv")

# Subperineurial data - Mdr65-GAL4
# df <- subperineurial.df %>%
#   group_by(Label) %>%
#   summarise(sum_Area = sum(Area)) %>%
#   ungroup() %>%
#   mutate(condition = case_when(
#     str_detect(Label, "Repo_GFP_control") ~ "Repo Control",
#     str_detect(Label, "Mdr_GFP_Control") ~ "Mdr65 Control",
#     str_detect(Label, "Mdr_GFP_lac_GD") ~ "Mdr65>Lac RNAi",
#     str_detect(Label, "Repo_GFP_lac") ~ "Repo>Lac RNAi")) %>%
#   mutate(channel = case_when(
#     str_detect(Label, "C1") ~ "Glial projection area",
#     TRUE ~ "Motor neuron axon projection area")) %>%
#   na.omit()
# 
# write_csv(df, "./Data/CH5_Glial_Areas_Subtype_Analysis/Results_Area_Mdr65_GAL4_clean.csv")

# Perineurial data - 46F-GAL4
# df <- perineurial.df %>%
#   group_by(Label) %>%
#   summarise(sum_Area = sum(Area)) %>%
#   ungroup() %>%
#   mutate(condition = case_when(
#     str_detect(Label, "Repo_Gal4_cd8_GFP_control") ~ "Repo Control",
#     str_detect(Label, "46F_Gal4_cd8_GFP_control") ~ "46F Control",
#     str_detect(Label, "46F_Gal4_cd8_GFP_GD") ~ "46F>Lac RNAi",
#     str_detect(Label, "Repo_Gal4_cd8_GFP_GD") ~ "Repo>Lac RNAi")) %>%
#   mutate(channel = case_when(
#     str_detect(Label, "C1") ~ "Glial projection area",
#     TRUE ~ "Motor neuron axon projection area")) %>%
#   na.omit()
# 
# write_csv(df, "./Data/CH5_Glial_Areas_Subtype_Analysis/Clean_dfs/Results_Area_46F_GAL4_clean.csv")
```

## Get stats - areas
```{r}
df <- wrapping.df %>%
  filter(channel == "Glial projection area")

variables <- c("sum_Area")

results <- map(variables, function(var) {
  
  # Check normality
  norm_result <- df %>%
    group_by(condition) %>%
    shapiro_test(!!sym(var)) %>%
    add_significance()
  
  # Print
  print(norm_result)
  
  # Kruskal-Wallis test
  kw_result <- df %>%
    kruskal_test(reformulate('condition', response = var))
  
  # Print
  print(kw_result)
  
  # Dunn test
  dunn_results <- df %>%
    dunn_test(reformulate('condition', response = var)) %>%
    add_significance() %>% 
    as_tibble()
})

# Combine results
final_results <- bind_rows(results)

write.csv(final_results, "./Output/Crawling_assay_automated/statistical_results_16092023_Nrv2_area_glia.csv", row.names = FALSE)
```

## Plot areas
```{r}
df$condition <- factor(df$condition, levels = c("Repo Control", "Repo>Lac RNAi", "Nrv2 Control", "Nrv2>Lac RNAi"))

ggplot(df, aes(x=condition, y=sum_Area, fill = condition)) + 
  geom_violin(color = NA, trim = TRUE, scale = "width") +
  geom_quasirandom(width = 0.25, size = 1) +
  facet_wrap(~ channel, scales = "free") + 
  stat_compare_means(comparisons = list(c("Repo Control", "Nrv2 Control"), c("Repo Control", "Repo>Lac RNAi"), c("Nrv2 Control", "Nrv2>Lac RNAi")), method = "wilcox.test", label = 'p.signif') +
  ggtitle("Comparison of glial and neuronal areas for Lac knockdown in wrapping glia") +
  xlab(NULL) + ylab(expression(paste("Area (",mu, m^2,")",sep=""))) +
  theme_bw() +
  # theme(panel.grid.major = element_blank(),
  #       panel.grid.minor = element_blank())+
  theme(plot.title = element_text(size = 12),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 10),)+
  theme(legend.position = "none") +
  scale_fill_viridis(discrete = TRUE, option = "plasma", alpha = 0.2) +
  geom_pointrange(stat = "summary", colour = "#C53270", size = 0.5) 

ggsave("/Users/daliagala/Library/CloudStorage/OneDrive-Nexus365/Thesis/Thesis-Scripts/Output/Plots/CH5_Nrv2_GAL4_Lac_areas.pdf",
       width = 12 * 0.62, height = 7 * 0.62,
       device = cairo_pdf)
```

## Get ratios
```{r}
ratios <- wrapping.df %>% 
  mutate(image_id = str_remove(Label, "_C[:digit:].tif")) %>%
  dplyr::select(-Label) %>%
  pivot_wider(values_from = sum_Area, names_from = channel) %>%
  mutate(ratio = `Glial projection area` / `Motor neuron axon projection area`)
```

## Get stats - ratios
```{r}
variables <- c("ratio")

results <- map(variables, function(var) {
  
  # Check normality
  norm_result <- ratios %>%
    group_by(condition) %>%
    shapiro_test(!!sym(var)) %>%
    add_significance()
  
  # Print
  print(norm_result)
  
  # Kruskal-Wallis test
  kw_result <- ratios %>%
    kruskal_test(reformulate('condition', response = var))
  
  # Print
  print(kw_result)
  
  # Dunn test
  dunn_results <- ratios %>%
    dunn_test(reformulate('condition', response = var)) %>%
    add_significance() %>% 
    as_tibble()
})

# Combine results
final_results_ratios <- bind_rows(results)

# write.csv(final_results_ratios, "./Output/Crawling_assay_automated/statistical_results_14092023_Nrv2_ratios.csv", row.names = FALSE)
```

# Plot ratios
```{r}
ratios$condition <- factor(ratios$condition, levels = c("Repo Control", "Repo>Lac RNAi", "Nrv2 Control", "Nrv2>Lac RNAi"))

ggplot(ratios, aes(x=condition, y=ratio, fill = condition)) + 
  geom_violin(color = NA, trim = TRUE, scale = "width") +
  geom_quasirandom(width = 0.25, size = 1) +
  stat_compare_means(comparisons = list(c("Repo Control", "Nrv2 Control"), c("Repo Control", "Repo>Lac RNAi"), c("Nrv2 Control", "Nrv2>Lac RNAi")), method = "t.test", label = 'p.signif') +
  ggtitle("Comparison of glial to neuronal area ratios for Lac knockdown in wrapping glia") +
  xlab(NULL) + ylab("Ratio (Glial/motor neuron projection area)") +
  theme_bw() +
  # theme(panel.grid.major = element_blank(),
  #       panel.grid.minor = element_blank())+
  theme(plot.title = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),)+
  theme(legend.position = "none") +
  scale_fill_viridis(discrete = TRUE, option = "plasma", alpha = 0.2) +
  geom_pointrange(stat = "summary", colour = "#C53270", size = 0.5) 

ggsave("/Users/daliagala/Library/CloudStorage/OneDrive-Nexus365/Thesis/Thesis-Scripts/Output/Plots/CH5_Nrv2_GAL4_Lac_ratios.pdf",
       width = 10 * 0.5, height = 7 * 0.5,
       device = cairo_pdf)
```

# Plot summary plots
```{r}
# Define a function to filter the dataframes
filter_conditions <- function(df) {
  df %>% 
    filter(condition %in% c("Repo Control", "Repo>Lac RNAi"))
}

# Create a list of your dataframes
list_of_dfs <- list(perineurial.df, subperineurial.df, wrapping.df)

# Use `purrr::map_dfr` to apply the filter function and then bind the rows
repo.df <- purrr::map_dfr(list_of_dfs, filter_conditions)
```

# Run stats on all dataframes
```{r}
wrapping.df <- wrapping.df %>%
  filter(!(condition %in% c("Repo Control", "Repo>Lac RNAi")))

perineurial.df <- perineurial.df %>%
  filter(!(condition %in% c("Repo Control", "Repo>Lac RNAi")))

subperineurial.df <- subperineurial.df %>%
  filter(!(condition %in% c("Repo Control", "Repo>Lac RNAi")))

process_dataframe <- function(df, control_group) {
  
  dev_area_cleaned <- df %>%
    mutate(Label = str_replace(Label, "_C[:digit:].tif", "")) %>%
    pivot_wider(id_cols = c(Label, condition), values_from = sum_Area, names_from = channel) %>%
    dplyr::rename("Neurite" = "Motor neuron axon projection area") %>%
    dplyr::rename("Glia" = "Glial projection area") %>%
    mutate(ratio_Glia_Neurite = Glia / Neurite) %>%
    pivot_longer(cols = c(Glia, Neurite, ratio_Glia_Neurite), names_to = "type")

dev_area_mean <- dev_area_cleaned %>%
    group_by(condition, type) %>%
    summarise(
        mean = mean(value)
    ) %>%
    ungroup()

  dev_area_foldchange <- left_join(
    filter(dev_area_mean, condition != control_group),
    filter(dev_area_mean, condition == control_group) %>%
      dplyr::select(type, "control_mean" = mean),
    by = "type"
  ) %>%
    mutate(foldchange = mean / control_mean)

  dev_area_statistics <- dev_area_cleaned %>%
    group_by(type) %>%
    wilcox_test(value ~ condition, ref.group = control_group) %>%
    dplyr::select(type, "condition" = group2, statistic, p, starts_with("n")) %>%
    left_join(dev_area_foldchange, by = c("type", "condition"))

  dev_area_statistics
}

list_of_dfs_for_combined <- list(perineurial.df, subperineurial.df, wrapping.df, repo.df)
control_groups <- c("46F Control", "Mdr65 Control", "Nrv2 Control", "Repo Control")

combined_result <- purrr::map2_dfr(list_of_dfs_for_combined, control_groups, process_dataframe)
write.csv(combined_result, "./Output/Crawling_assay_automated/statistical_results_area_all.csv", row.names = FALSE)
```

# Add significance and clean up labels
```{r}
area_statistics_for_plotting <- combined_result %>%
  mutate(p = case_when(
    p < 0.0001 ~ "**** < 0.0001",
    p < 0.001 ~ "*** < 0.001",
    p < 0.01 ~ "** < 0.01",
    p < 0.05 ~ "* < 0.05",
    TRUE ~ "N.S."
  )) %>%
  mutate(type = case_when(
    type == "Glia" ~ "Glial area",
    type == "Neurite" ~ "Neurite area",
    type == "ratio_Glia_Neurite" ~ "Ratio Glial/Neurite"
  ))
```

# Plot
```{r}
colours <- c(sequential_hcl(n = 7, palette = "Inferno", rev = FALSE)[3:5], "gray70")

gene_order_dev <- area_statistics_for_plotting %>%
  filter(type == "Glial area") %>%
  arrange(foldchange) %>% pull(condition)

area_statistics_for_plotting %>%
  mutate(condition = fct_relevel(condition, gene_order_dev)) %>%
  ggplot(aes(x = condition, y = foldchange, colour = p)) +
  geom_segment(aes(xend = condition, y = 1, yend = foldchange), colour = "gray50", size = 0.3) + 
  geom_point(size = 1.5) + 
  geom_hline(yintercept = 1, linetype = "dashed", colour = "gray70", size = 0.2) +
  coord_flip(ylim = c(0.25, 1.8)) +
  labs(
    x = "", 
    y = "Average foldchange over Control",
    colour = "P-value"
  ) + 
  scale_colour_manual(values = colours) + 
  facet_wrap(~ type) +
  theme_bw(base_size = 6) + 
  theme(
    legend.text = element_text(size = 4),
    legend.title = element_text(size = 5),
    axis.text.x = element_text(size = 3)
    ) +
  guides(colour = guide_legend(keywidth = 0.1, keyheight = 0.5)) -> dev_plot

dev_plot
# Save figure
ggsave("./Output/Plots/CH5_subtypes_areas_combined.pdf",
       width = 11 * 0.3937, height = 5 * 0.38937,
       device = cairo_pdf)
```

